---
title: ESMA 5015 Simulation
header-includes: \usepackage{color}
                 \usepackage{float}
output:
  html_document: default
  pdf_document:
    fig_caption: no
---

```{r, echo=FALSE, warning=FALSE, message=FALSE}
source("R/setup.rmd.R", local=TRUE)
setup.rmd(local.env=environment())
```
`r hl()$basefontsize()`
`r hl()$style()`

# General Information

0.1&nbsp;  [ESMA5015.pdf](ESMA5015.pdf) 
0.2&nbsp;  [Syllabus](syl.html)  
0.3&nbsp;  [Assignments](assign.html)  
0.4&nbsp;  [Resma3.RData](http://academic.uprm.edu/wrolke/Resma3/Resma3.RData?Ver 3.2) (Ver 3.2)

#  R

1.1&nbsp;  [Installation and updating](install.html)  
1.2&nbsp;  [R Markdown, HTML and Latex](Rmarkdown.html)  
1.3&nbsp;  [R basics](Rbasics.html)  
1.4&nbsp;  [Programming in R](writing.functions.html)  
1.5&nbsp;  [Random numbers and simulation](random.numbers.html)  
1.6&nbsp;  [Graphs with ggplot2](ggplot2.html)  
1.7&nbsp;  [List of base R commands](important.commands.html)  

#  Introduction 

2.1&nbsp;  [Basics](intro.html)  
2.2&nbsp;  [Monopoly](mon.html)  

# Probability

3.1&nbsp;  [Introduction](probability1.html)  
3.2&nbsp;  [Conditional Probability and Independence](probability2.html)  
3.3&nbsp;  [Random Variables and Random Vectors](probability3.html)  
3.4&nbsp;  [Expectation](probability4.html)  
3.5&nbsp;  [Inequalities and Limit Theorems](probability5.html)  
3.6&nbsp;  [Transformations](probability6.html)  
3.7&nbsp;  [Discrete Distributions](discrete.html)  
3.8&nbsp;  [Continuous Distributions](continuous.html)

# Generating Random Variables

4.1&nbsp;  [General Methods](generate1.html)  
4.2&nbsp;  [Fundamental Theorem](fund.html)    
4.3&nbsp;  [Special Cases](generate2.html)  

# Statistics

5.1&nbsp;  [Basic Statistics](stat1.html)  
5.3&nbsp;  [Verifying a Simulation](stat2.html)  
5.3&nbsp;  [A Realistic Example](stat3.html)

# Markov Chain Monte Carlo - MCMC

6.1&nbsp;  [Discrete - Time Markov Chains](mark1.html)  
6.2&nbsp;  [MCMC - Markov Chain Monte Carlo](mark2.html)  
6.3&nbsp;  [Gibbs Sampler](gibbs.html)  
6.4&nbsp;  [Slice Sampler](slice.html)  
6.5&nbsp;  [Bayesian Inference for Normal Distribution](normal.html)  

# Variance Reduction Methods

7.1&nbsp;  [Antithetic and Control Variables](vr1.html)  
7.2&nbsp;  [Conditioning and Importance Sampling](vr2.html)

# Additional Topics

8.1&nbsp;  [Optimization](opt2.html)  
8.2&nbsp;  [EM algorithm](em.html)  
8.3&nbsp;  [The Symmetric Random Walk in R](rw.html)  

# Student Exercises

9.1&nbsp;  [Risk!](risk.html)  
9.2&nbsp;  [Waiting Time](queue.html)


